# Generated by Django 5.2.5 on 2025-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_name', models.CharField(max_length=100)),
                ('current_power', models.FloatField()),
                ('today_energy', models.FloatField()),
                ('month_energy', models.FloatField()),
                ('runtime_minutes', models.IntegerField()),
            ],
        ),
    ]
