# Generated by Django 5.2.5 on 2025-08-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_sensorreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlugEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
